### ISSUE TITLE
Mixed up links in course manual (git client)

### ISSUE THREAD

**Issue by prstolpe** [egonw/scientificProgramming#2]
Under the section "Requirements" in the course manual, the links "nextflow" and "a Git client" lead to the same website about the git client download.

**Comment by egonw** [comment]
Thanks, I'll fix this this weekend.

**Comment by egonw** [comment]
Mmm... I cannot reproduce this. The source code looks okay, and when I test it in the PDF, it also works. Can you show me this on your machine tomorrow, so that I can see what is going on?

**Comment by prstolpe** [comment]
Last week I could still reproduce it when looking at the markdown file in student portal with two different browsers Safari and Chrome.

**Comment by egonw** [comment]
In this section? 

![image](https://user-images.githubusercontent.com/26721/66719817-d00fa480-edf4-11e9-9593-e7dfa93cf23a.png)

Because I just loaded a new PDF from Eleum and cannot reproduce it. Can you plz download the PDF and try with your favorite PDF viewer too?

**Comment by prstolpe** [comment]
Yes, just downloaded the file from student portal. I opened it in my pdf viewer and clicking on nextlfow clearly brings me to the git page. 

Mit freundlichen Grüßen
Raphael Stolpe

**Comment by egonw** [comment]
Okay, I now managed to reproduce it with the built-in PDF viewer of my Chrome. That indeed goes to the wrong website!! You found a Chrome bug :)

**Comment by egonw** [comment]
Also after downloading... sigh, what PDF viewer do you use?

**Comment by prstolpe** [comment]
I used preview on mac.

**Comment by egonw** [comment]
Another bugged tool then, it seems :(

I again double checked the Markdown source code, and the patch of Sept. 3 looks like (part of it):

![image](https://user-images.githubusercontent.com/26721/66719881-c175bd00-edf5-11e9-954e-ce9582a0a8cd.png)

(Of course, it could still be that the PDF created with [pandoc](https://pandoc.org/) has something to it that not all PDF viewers pick it up well... it can be an interaction bug, but my [Okular](https://okular.kde.org/) has no issues)

So, I have no idea how to fix it. That is, there is nothing I can change to the Markdown, I think...

**Comment by prstolpe** [comment]
That sounds very plausible to me. The only solution I could still imagine is changing around the order of items or make a list. That is mainly because the other links seem to have no such interaction. 
Otherwise I will just close the issue because it can’t be fixed.
